/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
              "on-tertiary-fixed-variant": "#910035",
              "surface-variant": "#2f3639",
              "on-primary-fixed-variant": "#004e60",
              "on-error-container": "#ffdad6",
              "primary-fixed-dim": "#4cd6ff",
              "primary-fixed": "#b7eaff",
              "secondary-container": "#05e777",
              "inverse-primary": "#00677f",
              "outline": "#859399",
              "on-secondary-container": "#00622e",
              "on-primary": "#003543",
              "on-primary-fixed": "#001f28",
              "tertiary": "#ffd1d6",
              "on-tertiary-fixed": "#400013",
              "on-background": "#dde3e7",
              "on-tertiary-container": "#9f003b",
              "on-tertiary": "#670023",
              "on-error": "#690005",
              "tertiary-fixed": "#ffd9dd",
              "outline-variant": "#3c494e",
              "error": "#ffb4ab",
              "secondary": "#7dffa2",
              "tertiary-fixed-dim": "#ffb2bc",
              "border": "#2E3A59",
              "on-primary-container": "#00566a",
              "surface-container": "#1a2123",
              "inverse-surface": "#dde3e7",
              "tertiary-container": "#ffa9b5",
              "on-secondary-fixed-variant": "#005226",
              "inverse-on-surface": "#2b3134",
              "on-secondary-fixed": "#00210b",
              "surface-dim": "#0e1417",
              "error-container": "#93000a",
              "text-secondary": "#8F9BB3",
              "surface-container-high": "#242b2e",
              "text-primary": "#FFFFFF",
              "secondary-fixed": "#62ff96",
              "background": "#12131A",
              "warning": "#FFAA00",
              "primary": "#a4e6ff",
              "surface-bright": "#333a3d",
              "surface-tint": "#4cd6ff",
              "surface-container-low": "#161d1f",
              "on-surface": "#dde3e7",
              "primary-container": "#00d1ff",
              "on-secondary": "#003918",
              "surface-container-lowest": "#090f12",
              "surface-container-highest": "#2f3639",
              "secondary-fixed-dim": "#00e475",
              "surface": "#1A1C24",
              "on-surface-variant": "#bbc9cf",
              "trading-success": "#00E676",
              "trading-error": "#FF3D71"
      },
      "borderRadius": {
              "DEFAULT": "0.25rem",
              "lg": "0.5rem",
              "xl": "0.75rem",
              "full": "9999px"
      },
      "spacing": {
              "md": "16px",
              "xs": "4px",
              "lg": "24px",
              "2xl": "48px",
              "sm": "8px",
              "xl": "32px"
      },
      "fontFamily": {
              "label-sm": ["Geist Mono", "JetBrains Mono", "monospace"],
              "h1": ["Geist Sans", "Inter", "system-ui"],
              "data-tabular": ["JetBrains Mono", "monospace"],
              "headline-lg": ["Geist", "sans-serif"],
              "headline-md": ["Geist", "sans-serif"],
              "body-md": ["Geist Sans", "Inter", "system-ui"],
              "h2": ["Geist Sans", "Inter", "system-ui"]
      },
      "fontSize": {
              "label-sm": ["0.75rem", { "lineHeight": "1.0", "letterSpacing": "0.05em", "fontWeight": "500" }],
              "h1": ["1.75rem", { "lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "700" }],
              "data-tabular": ["0.875rem", { "lineHeight": "1.2", "fontWeight": "500" }],
              "headline-lg": ["1.75rem", { "lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "700" }],
              "headline-md": ["1.25rem", { "lineHeight": "1.3", "fontWeight": "600" }],
              "body-md": ["0.875rem", { "lineHeight": "1.5", "fontWeight": "400" }],
              "h2": ["1.25rem", { "lineHeight": "1.3", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
