import sqlite3
import pandas as pd
from datetime import datetime
from typing import List, Dict, Any, Optional
import cachetools
import logging
import os
import requests
from concurrent.futures import ThreadPoolExecutor, as_completed

from ..models.schemas import MarketData, MarketType

logger = logging.getLogger(__name__)

# Constants for backward compatibility with other services (news, agents)
INDONESIAN_STOCKS: Dict[str, str] = {
    "BBCA.JK":  "Bank Central Asia",
    "BBRI.JK":  "Bank Rakyat Indonesia",
    "BMRI.JK":  "Bank Mandiri",
    "TLKM.JK":  "Telkom Indonesia",
    "ASII.JK":  "Astra International",
}
COMMODITIES: Dict[str, str] = {}
INDICES: Dict[str, str] = {}
ALL_SYMBOLS = {**INDONESIAN_STOCKS}

# Path to the IDX-API sqlite database generated by Deno
DB_PATH = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', 'idx_scraper', 'data', 'database.sqlite'))

class DataService:
    """
    Service layer untuk mengambil data pasar secara lokal dari SQLite (hasil scraping IDX-API Deno).
    """

    def __init__(self):
        self._realtime_cache = cachetools.TTLCache(maxsize=200, ttl=60)
        self._summary_cache = cachetools.TTLCache(maxsize=10, ttl=300)
        # Shared HTTP session untuk reuse koneksi ke Deno API (lebih efisien)
        self._session = requests.Session()
    
    def _get_connection(self):
        return sqlite3.connect(DB_PATH)

    def _get_market_type(self, symbol: str) -> MarketType:
        return MarketType.STOCK

    def _fetch_single(self, symbol: str) -> Optional[MarketData]:
        cached = self._realtime_cache.get(symbol)
        if cached: 
            return cached
        
        # Backend python expects .JK suffix, but DB stores pure ticker e.g. BBCA
        clean_symbol = symbol.replace('.JK', '').upper()
        
        try:
            # PRIMARY LAYER: Deno REST API
            response = self._session.get(f"http://localhost:52060/trading/company/{clean_symbol}/daily?limit=1", timeout=3)
            if response.status_code == 200:
                data_json = response.json().get('data', [])
                if data_json:
                    latest = data_json[0]
                    name = clean_symbol  # Temporary, real name from profile
                    
                    price = float(latest.get('close', 0.0))
                    prev = float(latest.get('previous', 0.0))
                    change = float(latest.get('change', 0.0))
                    change_pct = (change / prev * 100) if prev > 0 else 0.0
                    
                    updated_at_str = latest.get('updatedAt')
                    if updated_at_str:
                        # Handle trailing Z for isoformat
                        last_update = datetime.fromisoformat(updated_at_str.replace('Z', '+00:00')).replace(tzinfo=None)
                    else:
                        last_update = datetime.now()

                    market_data = MarketData(
                        symbol=symbol,
                        name=name,
                        price=price,
                        change=change,
                        change_percent=change_pct,
                        volume=int(latest.get('volume', 0)),
                        open=float(latest.get('open', 0.0)),
                        high=float(latest.get('high', 0.0)),
                        low=float(latest.get('low', 0.0)),
                        close=price,
                        last_update=last_update,
                        market_type=self._get_market_type(symbol),
                    )
                    self._realtime_cache[symbol] = market_data
                    return market_data
        except Exception as e:
            logger.warning(f"⚠️ Deno API Fetch fail for {symbol}, fallback SQLite: {e}")
            
        # FALLBACK LAYER: SQLite Database
        try:
            with self._get_connection() as con:
                # Get company profile for name
                prof = pd.read_sql_query("SELECT * FROM company_profile WHERE code = ?", con, params=(clean_symbol,))
                name = prof.iloc[0]['name'] if not prof.empty else clean_symbol
                
                # Get latest trading summary
                df = pd.read_sql_query("SELECT * FROM stock_summary WHERE code = ? ORDER BY id DESC LIMIT 1", con, params=(clean_symbol,))
                if df.empty:
                    # Fallback to trading_daily if summary doesn't exist yet
                    df = pd.read_sql_query("SELECT * FROM trading_daily WHERE code = ? ORDER BY id DESC LIMIT 1", con, params=(clean_symbol,))
                    if df.empty:
                        return None
                    
                latest = df.iloc[0]
                price = float(latest['close'])
                prev = float(latest['previous'])
                change = float(latest['change'])
                change_pct = (change / prev * 100) if prev > 0 else 0.0
                
                if 'updated_at' in df.columns and pd.notna(latest.get('updated_at')):
                    try:
                        last_update = pd.to_datetime(latest['updated_at']).to_pydatetime()
                    except Exception:
                        last_update = datetime.now()
                elif 'date' in df.columns and pd.notna(latest.get('date')):
                    try:
                        # stock_summary uses unix timestamp in milliseconds
                        last_update = datetime.fromtimestamp(int(latest['date']) / 1000.0)
                    except Exception:
                        last_update = datetime.now()
                else:
                    last_update = datetime.now()

                data = MarketData(
                    symbol=symbol,  # keep original requested symbol
                    name=name,
                    price=price,
                    change=change,
                    change_percent=change_pct,
                    volume=int(latest['volume']),
                    open=float(latest['open']),
                    high=float(latest['high']),
                    low=float(latest['low']),
                    close=price,
                    last_update=last_update,
                    market_type=self._get_market_type(symbol),
                )
                self._realtime_cache[symbol] = data
                return data
        except Exception as e:
            logger.error(f"Error fetch {symbol} from SQLite: {e}")
            return None

    def _make_fallback(self, symbol: str) -> MarketData:
        return MarketData(
            symbol=symbol,
            name=symbol,
            price=0.0, change=0.0, change_percent=0.0,
            volume=0, open=0.0, high=0.0, low=0.0, close=0.0,
            last_update=datetime.now(),
            market_type=self._get_market_type(symbol),
        )

    def _fetch_batch(self, symbols: List[str]) -> Dict[str, Optional[MarketData]]:
        return {s: self._fetch_single(s) for s in symbols}

    def get_market_data(self, symbols: Optional[List[str]] = None) -> List[MarketData]:
        if symbols is None:
            symbols = list(self.get_all_symbols().keys())[:100] # Limit to 100 to avoid UI crash
            
        results = []
        with ThreadPoolExecutor(max_workers=10) as executor:
            future_to_symbol = {executor.submit(self._fetch_single, symbol): symbol for symbol in symbols}
            for future in as_completed(future_to_symbol):
                symbol = future_to_symbol[future]
                try:
                    data = future.result()
                    if data:
                        results.append(data)
                    else:
                        results.append(self._make_fallback(symbol))
                except Exception as exc:
                    logger.error(f"{symbol} generated an exception: {exc}")
                    results.append(self._make_fallback(symbol))
        return results

    def get_all_assets(self) -> List[MarketData]:
        return self.get_market_data(list(self.get_all_symbols().keys())[:50])

    def get_historical_data(self, symbol: str, period: str = "3mo") -> pd.DataFrame:
        cache_key = f"hist_{symbol}_{period}"
        cached = self._realtime_cache.get(cache_key)
        if cached is not None:
            return cached

        try:
            import yfinance as yf
            ticker = yf.Ticker(symbol)
            
            # Map period to interval for better candlestick density
            interval = "1d"
            if period == "1d":
                interval = "5m"
            elif period == "5d":
                interval = "15m"
                
            df = ticker.history(period=period, interval=interval)
            if not df.empty:
                self._realtime_cache[cache_key] = df
                return df
        except Exception as e:
            logger.error(f"Error fetch historis {symbol} with yfinance: {e}")
            
        return pd.DataFrame()

    def get_market_summary(self) -> Dict[str, Any]:
        return {
            "index": "IHSG", "price": 7000, "change": 10,
            "change_percent": 0.1, "volume": 100000,
            "timestamp": datetime.now().isoformat(),
        }

    def get_symbol_info(self, symbol: str) -> Dict[str, Any]:
        clean_symbol = symbol.replace('.JK', '').upper()
        
        # PRIMARY LAYER: Deno REST API
        try:
            response = self._session.get(f"http://localhost:52060/companies/{clean_symbol}", timeout=3)
            if response.status_code == 200:
                data_json = response.json().get('data', {})
                prof = data_json.get('profile', {})
                detail = data_json.get('detail', {})
                if prof:
                    return {
                        "symbol": symbol,
                        "name": prof.get('name', clean_symbol),
                        "sector": detail.get('sector', 'BEI'),
                        "industry": detail.get('industry', 'BEI'),
                        "market_cap": 0,
                        "description": detail.get('businessActivity', 'Data resmi perusahaan publik dari Bursa Efek Indonesia.'),
                        "directors": detail.get('directors', '[]'),
                        "shareholders": detail.get('shareholders', '[]')
                    }
        except Exception as e:
            logger.warning(f"⚠️ Deno API Info fail for {symbol}, fallback SQLite: {e}")
            
        # FALLBACK LAYER: SQLite
        try:
            with self._get_connection() as con:
                prof = pd.read_sql_query("SELECT * FROM company_profile WHERE code = ?", con, params=(clean_symbol,))
                if not prof.empty:
                    return {
                        "symbol": symbol,
                        "name": prof.iloc[0]['name'],
                        "sector": "BEI",
                        "industry": "BEI",
                        "market_cap": 0,
                        "description": "Data resmi perusahaan publik dari Bursa Efek Indonesia.",
                    }
        except Exception:
            pass
        return {"symbol": symbol, "name": symbol}

    def get_ihsg_constituents(self, refresh: bool = False) -> Dict[str, str]:
        return self.get_all_symbols()

    def get_all_symbols(self) -> Dict[str, str]:
        try:
            with self._get_connection() as con:
                prof = pd.read_sql_query("SELECT code, name FROM company_profile", con)
                return {f"{row['code']}.JK": row['name'] for _, row in prof.iterrows()}
        except Exception:
            return {"BBCA.JK": "Bank Central Asia"}

    def search_tickers(self, query: str, count: int = 20) -> List[Dict[str, Any]]:
        return []
